language: python
os: linux
env:
 - DIST=precise
 - DIST=trusty
 - DIST=xenial

python:
   - "2.7_with_system_site_packages"

addons:
   apt:
      packages:
         - libhdf5-serial-dev
         - netcdf-bin
         - libnetcdf-dev

before_install:
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   - sudo apt-get update -qq
   - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-mpltoolkits.basemap

install:
   - sudo pip install .

script:
   - pip install coveralls pep8
   - nosetests -v --with-coverage --cover-erase --cover-package=verif
   - verif examples/raw.txt examples/kf.txt -m mae -f test.png

after_success:
   - coveralls
