language: python
python:
   - "2.7_with_system_site_packages"

before_install:
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"

install:
   - sudo apt-get install gfortran
   - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
   - pip install coveralls pep8
   - sudo python setup.py build
   - sudo python setup.py install

script:
   - nosetests --with-coverage --cover-erase --cover-package=verif

after_success:
   - coveralls

env:
 - DIST=lucid

os: linux
